"""empty message

Revision ID: a320ea82a465
Revises: 
Create Date: 2022-05-04 13:11:06.421119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a320ea82a465'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('archive', sa.Boolean(), nullable=True))
    op.add_column('comments', sa.Column('archive', sa.Boolean(), nullable=True))
    op.add_column('photos', sa.Column('archive', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('archive', sa.Boolean(), nullable=True))
    op.add_column('todos', sa.Column('archive', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('archive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'archive')
    op.drop_column('todos', 'archive')
    op.drop_column('posts', 'archive')
    op.drop_column('photos', 'archive')
    op.drop_column('comments', 'archive')
    op.drop_column('albums', 'archive')
    # ### end Alembic commands ###
